"""add user admin and audited flags

Revision ID: 40526f93ceed
Revises: 9f69b1840a73
Create Date: 2026-06-24 16:37:03.235984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40526f93ceed'
down_revision: Union[str, Sequence[str], None] = '9f69b1840a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('is_audited', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_audited')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
