"""add comments to task

Revision ID: 9f69b1840a73
Revises: b38e71ac3209
Create Date: 2026-06-23 15:55:29.797245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f69b1840a73'
down_revision: Union[str, Sequence[str], None] = 'b38e71ac3209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'comments')
    # ### end Alembic commands ###
