"""add task duedate and description columns

Revision ID: aca9d22b4dbc
Revises: a73a07e7dd4a
Create Date: 2026-06-16 15:29:07.451170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca9d22b4dbc'
down_revision: Union[str, Sequence[str], None] = 'a73a07e7dd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duedate', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'duedate')
    # ### end Alembic commands ###
