"""add_audit_periods_table

Revision ID: be2af9f21169
Revises: 4e9aadb4fe66
Create Date: 2026-06-25 12:46:20.110307

"""
import secrets
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2af9f21169'
down_revision: Union[str, Sequence[str], None] = '4e9aadb4fe66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_periods',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('ended_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Data migration: seed one open AuditPeriod for every currently-audited user.
    # This avoids retroactive faltas from before the deploy.
    conn = op.get_bind()
    now_iso = datetime.now(timezone.utc).isoformat()
    audited_users = conn.execute(
        sa.text("SELECT id FROM users WHERE is_audited = TRUE")
    ).fetchall()
    if audited_users:
        rows = [
            {"id": secrets.token_hex(16), "user_id": row[0], "started_at": now_iso}
            for row in audited_users
        ]
        conn.execute(
            sa.text(
                "INSERT INTO audit_periods (id, user_id, started_at) VALUES (:id, :user_id, :started_at)"
            ),
            rows,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_periods')
    # ### end Alembic commands ###
